resource_group_name = "uipath-rg"
resource_group_location = "East US"
admin_username      = "uipathadmin"
admin_password      = "StrongPassword123!"
sql_server_name      = "farhaan-sql-server"
sql_database_name    = "uipathdb"
sql_admin_username   = "sqladminfarhaan"
sql_admin_password   = "SuperStrongP@ssword123!"
